# Generated by Django 2.2.2 on 2019-07-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptuj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='link',
            field=models.CharField(default='www', max_length=256),
            preserve_default=False,
        ),
    ]
