# Generated by Django 2.2.2 on 2019-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptuj', '0003_animal_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age_years',
            field=models.IntegerField(default=0),
        ),
    ]
