# Generated by Django 2.2.2 on 2019-07-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptuj', '0004_auto_20190724_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.IntegerField(choices=[(1, 'M'), (2, 'F'), (3, 'both')]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='shelter_group',
            field=models.IntegerField(choices=[(1, 'Warszawa'), (2, 'Kraków'), (3, 'Wrocław'), (4, 'Trójmiasto'), (5, 'Poznań'), (6, 'Łódź'), (7, 'Katowice'), (8, 'Lublin'), (0, 'all')]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.IntegerField(choices=[(1, 'dog'), (2, 'cat'), (3, 'both')]),
        ),
    ]
